-- 코드를 입력하세요

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS DATE_FORMAT, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE)=2022 && MONTH(SALES_DATE)=3

UNION

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS DATE_FORMAT, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE)=2022 && MONTH(SALES_DATE)=3

ORDER BY DATE_FORMAT,PRODUCT_ID,USER_ID